version: "3.2"
services:
  my-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    #    ports:
    #      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      POSTGRES_PASSWORD: root
